### ISSUE TITLE
Jitsi-go-openid just returns 404 error

### ISSUE THREAD

**Issue by motey** [mod242/jitsi-go-openid#1]
Hello, thanks for this project. Exactly what i was looking for :heart: 

i just tried to setup everything. Iam running pretty standard instance of https://github.com/jitsi/docker-jitsi-meet behind a traefik reverse proxy.
Now i tried to integrate your project with an extra service.

```yaml
[...] # jitsi docker containers
    jitsi-openid:
        image: mod242/jitsi-go-openid:latest
        restart: always
        environment:
        - JITSI_SECRET=${JWT_APP_SECRET}           # Must match the jwt_secret from your Jitsi configuration
        - JITSI_URL=https://jitsi.mydomain.com      # Base URL of your Jitsi instance
        - JITSI_SUB=jitsi               # Must match the JWT_APP_ID from your Jitsi configuration
        - ISSUER_BASE_URL=https://auth.mydomain.com/application/o/jitsi/  # Base URL of your OpenID Connect provider
        - BASE_URL=https://jitsi.mydomain.com        # Public base URL of this application (should run behind a reverse proxy)
        - CLIENT_ID=${OIDC_CLIENT_ID}            # Client ID from your OAuth provider
        - SECRET=${OIDC_SECRET}                 # Client secret from your OAuth provider
        - PREJOIN=false                # Whether the prejoin page should be displayed again after authentication
        - DEEPLINK=true                # Whether the callback should use a deep link for redirect to ensure the originating client (Desktop, iOS, Android) is used
        - NAME_KEY=name                # Key for the users name from the OAuth token (defaults to name, but can be given_name or any other key present in the token)
        #expose: 
        #- 3001
        labels:
        - "traefik.enable=true"
        - "traefik.http.services.srv-${INSTANCE_NAME}-oidc.loadbalancer.server.port=3001"
        - "traefik.http.routers.rt-${INSTANCE_NAME}-oidc.service=srv-${INSTANCE_NAME}-oidc"
        - "traefik.http.routers.rt-${INSTANCE_NAME}-oidc.entrypoints=webtls"
        - "traefik.http.routers.rt-${INSTANCE_NAME}-oidc.rule=Host(`jitsi.mydomain.com`) && PathPrefix(`/jitsi-openid/`)"
        - "traefik.http.routers.rt-${INSTANCE_NAME}-oidc.tls=true"
        - "traefik.http.routers.rt-${INSTANCE_NAME}-oidc.tls.certResolver=letsencrypt-resolver"
        networks:
        - meet.jitsi # -> Your Jitsi Network (if run co-located and exposed via Jitsi-Web)
        - front # my treafik front network
```

When i now create a new room (named "MyNewRoom" in this example) and try to login i get a redirect as expected. The auth token url seems to be generated as described in the docs. 
The logs of the "jitsi-go-openid"-container also registers the call:
```
[GIN] 2024/08/04 - 18:40:09 | 404 |         629ns |     171.28.0.15 | GET      "/jitsi-openid/authenticate?state=%7B%22room%22%3A%22MyNewRoom%22%2C%22roomSafe%22%3A%22mynewroom%22%2C%22config.prejoinConfig.enabled%22%3Afalse%2C%22config.startWithVideoMuted%22%3Atrue%7D&room=MyNewRoom"
```
But as we can see it seems to generate a 404 error somewhere. In the browser i also just get a 404 error as answer.
Now my question is, where does it errors out. 

It is the "jitsi-go-openid"-container trying to contact my OIDC Provider?
Can i set logging more verbose with an env var?

If you have any hint for me i would be very thankful :heart:
